### ISSUE TITLE
Doesn't start after fresh install

### ISSUE THREAD

**Issue by janxkoci** [TenderOwl/Norka#19]
I just installed Norka today, tried to launch it from AppCenter and Slingshot, but it failed (icon briefly appeared in the dock).

After trying to start it from terminal I got this error:

```bash
jena@dell:~$ com.github.tenderowl.norka 
Traceback (most recent call last):
  File "/usr/bin/com.github.tenderowl.norka", line 53, in <module>
    from norka import main
  File "/usr/lib/python3.6/site-packages/norka/main.py", line 29, in <module>
    from norka.widgets.preferences_dialog import PreferencesDialog
  File "/usr/lib/python3.6/site-packages/norka/widgets/preferences_dialog.py", line 30, in <module>
    gi.require_version('Granite', '1.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Granite not available
```

According to `apt search norka` I should have version `0.3.3`.

**Comment by amka** [comment]
Thanks for your reply. Will investigate it soon.
Could you clarify your distro and version?

**Comment by amka** [comment]
As of hotfix try to install this
```
sudo apt install gir1.2-gtkspell3-3.0 gir1.2-gtksource-3.0 gir1.2-granite-1.0
```
Checked on newly installed 5.1.6 it is the only libraries I've installed to run Norka properly.
I will include them in the next build.

**Comment by janxkoci** [comment]
Here is my system info:

![Snímek z 2020-07-18 13-25-43](https://user-images.githubusercontent.com/19331850/87851564-3bddeb00-c8fa-11ea-8bcd-2f7e733bdb64.png)

Installing the suggested packages solved it, Norka now starts succesfully, there are just some warnings now:

```bash
jena@dell:~$ com.github.tenderowl.norka
[INFO] 2020-07-18 13:27:14 Storage folder created at /home/jena/.local/share/Norka
[INFO] 2020-07-18 13:27:14 Storage located at /home/jena/.local/share/Norka/storage.db

** (com.github.tenderowl.norka:15370): CRITICAL **: 13:27:14.298: check_range: assertion 'spell->priv->speller != NULL' failed
```

**Comment by SamMorrowDrums** [comment]
Can confirm the suggestion worked for me too. It's a shame the issue has coincided with the blog post and featured app in the store stuff, as less tech savvy users won't launch from console to see the error. However good luck, I hope the new release is out soon and thanks for mentioning which packages were missing!

**Comment by amka** [comment]
Thank you for reply. It is definitely my bad, I was sure about store review as it is done in Google or apple stores. So for now we have to wait till fixed version goes to appcenter for everyone.

Thank you once again for giving a chance for Norka.

**Comment by megatux** [comment]
Similar issue, but worked after installing missing deps. Thx
```
$ com.github.tenderowl.norka 
Traceback (most recent call last):
  File "/usr/bin/com.github.tenderowl.norka", line 53, in <module>
    from norka import main
  File "/usr/lib/python3.6/site-packages/norka/main.py", line 33, in <module>
    gi.require_version('GtkSpell', '3.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GtkSpell not available

```

**Comment by coyoterj** [comment]
> As of hotfix try to install this
> 
> ```
> sudo apt install gir1.2-gtkspell3-3.0 gir1.2-gtksource-3.0 gir1.2-granite-1.0
> ```
> 
> Checked on newly installed 5.1.6 it is the only libraries I've installed to run Norka properly.
> I will include them in the next build.

Hello,
Same problem when installing today, solved!

My system info:
elementary os 5.1.6 Hera
Linux 5.4.0-42-generic
GTK 3.22.30
Dual-Core Intel® Core™ i5-4210U CPU @ 1.70GHz
Intel Corporation Haswell-ULT Integrated Graphics Controller

Thanks!
