### ISSUE TITLE
Crash on start (elementary OS 5.1.6 Hera)

### ISSUE THREAD

**Issue by danrabbit** [TenderOwl/Norka#20]
When installing Norka from packaging and running on a fresh elementary OS 5.1.6, it crashes on start with the following Terminal output:

```
Traceback (most recent call last):
  File "/usr/bin/com.github.tenderowl.norka", line 53, in <module>
    from norka import main
  File "/usr/lib/python3.6/site-packages/norka/main.py", line 30, in <module>
    gi.require_version('Granite', '1.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Granite not available
```

**Comment by amka** [comment]
Hey! I've added it as dependencies to deb control file and pushed version 0.4.2 to appcenter. Now it is awaiting review.
By now issue reviewed in #19 with a hotfix solution.

My bad. I thought such cases will be the reason to decline with a human review on the submission process.

**Comment by amka** [comment]
Oh, seems like it was found in the review. @danrabbit do you have this issue with 0.4.2?

**Comment by danrabbit** [comment]
Yes this is the 0.4.2 package that was built by AppCenter Dashboard.

It looks like you have both a `deb-packaging` branch and a `debian` folder in your master branch. This is probably causing some issues if they're out of sync. You should have either one or the other, but not both

**Comment by amka** [comment]
Thank you for the advise. Pushed 0.4.3 to review.

**Comment by danrabbit** [comment]
It looks like we have a new crash point :)

```
Traceback (most recent call last):
  File "/usr/bin/com.github.tenderowl.norka", line 53, in <module>
    from norka import main
  File "/usr/lib/python3.6/site-packages/norka/main.py", line 31, in <module>
    gi.require_version('GtkSpell', '3.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GtkSpell not available
```

**Comment by stormchaser3000** [comment]
> It looks like we have a new crash point :)
> 
> ```
> Traceback (most recent call last):
>   File "/usr/bin/com.github.tenderowl.norka", line 53, in <module>
>     from norka import main
>   File "/usr/lib/python3.6/site-packages/norka/main.py", line 31, in <module>
>     gi.require_version('GtkSpell', '3.0')
>   File "/usr/lib/python3/dist-packages/gi/__init__.py", line 130, in require_version
>     raise ValueError('Namespace %s not available' % namespace)
> ValueError: Namespace GtkSpell not available
> ```

I was able to fix this by installing gir1.2-gtkspell3-3.0

**Comment by amka** [comment]
@stormchaser3000 yup this is a known bug due to lack of dependencies in deb package. Hotfix described in #19 
@danrabbit this is kinda weird because `control`  file contains these libraries. Maybe I miss something in the release or build process? I did a fresh build on my machine and tested it against fresh Elementary 5.1.6 and it works just fine, but it was a manual build.

**Comment by danrabbit** [comment]
@amka it looks like these packages are listed under `build-depends` which means they will be installed to the build environment while your source code is compiled. If these packages are runtime dependencies that need to be installed to the users' system then you'll need to list them further below under `depends`

**Comment by amka** [comment]
@danrabbit thanks for the advice. Now, when I pushed runtime dependencies to control file and made a new release, how to push it to AppCenter?

**Comment by danrabbit** [comment]
Hey @amka the latest one is writeas:

```
Traceback (most recent call last):
  File "/usr/bin/com.github.tenderowl.norka", line 53, in <module>
    from norka import main
  File "/usr/lib/python3.6/site-packages/norka/main.py", line 40, in <module>
    from norka.widgets.preferences_dialog import PreferencesDialog
  File "/usr/lib/python3.6/site-packages/norka/widgets/preferences_dialog.py", line 28, in <module>
    from norka.services.writeas import Writeas
  File "/usr/lib/python3.6/site-packages/norka/services/writeas.py", line 25, in <module>
    import writeas
ModuleNotFoundError: No module named 'writeas'

```

**Comment by amka** [comment]
@danrabbit I've updated deb files by adding python packages to build. After building the .deb package via `debuild -b -us -uc` I've tested it on fresh Elementary install and it worked absolutely fine.

I'm not experienced with .deb packaging and AppCenter, for now, I just see that there are issues but what exactly goes wrong?

**Comment by danrabbit** [comment]
It looks like you added a new feature that requires a new runtime dependency (writeas), but didn't update the runtime dependencies in your packaging. The result is that Norka crashes immediately when you try to start it.

**Comment by amka** [comment]
Yup, that is the problem I tried to solve in current deb-packaging https://github.com/TenderOwl/Norka/blob/8f5b014b5d566db19577ac90832c72c4f927bba6/debian/rules#L26.

And after these changes, I tested it as mentioned above. Does this problem still exist?

**Comment by danrabbit** [comment]
@amka I don't think you have access to the internet like that on the builds server, so my guess would be that the package would fail to build. I suppose you can try it. Another option might be using a git submodule for writeas

**Comment by amka** [comment]
Ok, but can I see logs of the current build? Because seems like build bot doesn't start any issues about it.
Let's make it clear, it will be much more convenient and easier for us to see what's exactly goes wrong. Just wanna fix it as quickly as I can, but don't have enough info about crashes or failed builds...

**Comment by danrabbit** [comment]
@amka have you submitted another build? If a build fails, you should get an automatic issue report filed with a build log

**Comment by amka** [comment]
@danrabbit ah yes, the current build of 0.4.5 was sent to the store.

**Comment by cassidyjames** [comment]
Was just looking at the review for 0.4.5 today. The deb (http://packages.elementary.io/testing/pool/main/c/com.github.tenderowl.norka/com.github.tenderowl.norka0.4.5-28400a.deb) seemed to build fine, and installs and runs on elementary OS 5.1.7 Hera now.

**Comment by amka** [comment]
Not as easy as flatpak but it is awesome news!
