### ISSUE TITLE
Norka crashes in Elementary Hera 5.1

### ISSUE THREAD

**Issue by cyranowebdev** [TenderOwl/Norka#22]
Just installed to try it, but it keeps crashing, never managed to run it.

**Comment by amka** [comment]
Hello! Try to use this one https://github.com/TenderOwl/Norka/issues/19#issuecomment-660154638
I'll do my best with the help of ElementaryOS guys to push new releases as soon as possible.

**Comment by cyranowebdev** [comment]
Thanks! Tried the hot fix and it worked so far. :slightly_smiling_face:
