### ISSUE TITLE
Increase minimum preferences window size and make it non-resizable

### ISSUE THREAD

**Issue by hanaral** [TenderOwl/Norka#23]
Right now the preferances panel doesn't seem to have a minimum size, so it can spawn too small and block the settings at the bottom. I recommend making the minimum window size big enough to fit all the settings and also so that the panel looks equal.

**Comment by megatux** [comment]
Notice same issue. Screenshot:
![Captura de pantalla de 2020-07-28 12-08-39](https://user-images.githubusercontent.com/850020/88684426-3b4c0e00-d0cb-11ea-9c81-15f3bffd87ad.png)

**Comment by amka** [comment]
It makes sense. Thanks for your suggestion.
