### ISSUE TITLE
update failure

### ISSUE THREAD

**Issue by janxkoci** [TenderOwl/Norka#24]
Hi, I tried to update to the new version of Norka, but the update failed (all other updates went through successfully). When I tried to run the update from terminal, I got this output at the end:

```
Následující balíky budou aktualizovány:
  com.github.tenderowl.norka
1 aktualizováno, 0 nově instalováno, 0 k odstranění a 0 neaktualizováno.
Nutno stáhnout 0 B/663 kB archivů.
Po této operaci bude na disku použito dalších 3 178 kB.
Chcete pokračovat? [Y/n] 
(Načítá se databáze … nyní je nainstalováno 243697 souborů a adresářů.)
Připravuje se nahrazení …/com.github.tenderowl.norka_0.4.5_amd64.deb …
Rozbaluje se com.github.tenderowl.norka (0.4.5) přes (0.3.3) …
dpkg: chyba při zpracovávání archivu /var/cache/apt/archives/com.github.tenderowl.norka_0.4.5_amd64.deb (--unpack):
 zkouším přepsat soubor „/usr/bin/chardetect“, který je také v balíku python-chardet 3.0.4-1
Při zpracování nastaly chyby:
 /var/cache/apt/archives/com.github.tenderowl.norka_0.4.5_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

There seems to be some kind of conflict with the package `python-chardet`, maybe?

My current version is `0.3.3`, I think.

**Comment by megatux** [comment]
Same error here. Does not update from App center or console. Error msg (in Spanish) :

```
$ sudo apt upgrade
.......
Se actualizarán los siguientes paquetes:
  com.github.tenderowl.norka
1 actualizados, 0 nuevos se instalarán, 0 para eliminar y 0 no actualizados.
Se necesita descargar 0 B/663 kB de archivos.
Se utilizarán 3.178 kB de espacio de disco adicional después de esta operación.
¿Desea continuar? [S/n] 
(Leyendo la base de datos ... 460751 ficheros o directorios instalados actualmente.)
Preparando para desempaquetar .../com.github.tenderowl.norka_0.4.5_amd64.deb ...
Desempaquetando com.github.tenderowl.norka (0.4.5) sobre (0.3.3) ...
dpkg: error al procesar el archivo /var/cache/apt/archives/com.github.tenderowl.norka_0.4.5_amd64.deb (--unpack):
 intentando sobreescribir `/usr/bin/chardetect', que está también en el paquete python-chardet 3.0.4-1
Se encontraron errores al procesar:
 /var/cache/apt/archives/com.github.tenderowl.norka_0.4.5_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by amka** [comment]
Confirmed.
Unfortunately for me, dpkg tries to install `python-chardet` as a dependency of `python3-requests` package which causes the conflict. I have an idea of how to fix that but need some time to test.

**Comment by megatux** [comment]
It would be nice to know if this issue could have been detected before, in the Elementaryos app validation store process, to improve the overall apps certification process. (if this does not apply, ignore this msg. I know there is some validation process when publishing apps, but I'm not an app developer, yet :) )

**Comment by amka** [comment]
@megatux my thoughts based on experience with Microsoft, Apple, and Google stores were totally wrong. I think ElementaryOS guys have not enough time to make review works it the same way. And the ability to control publication will be available in the future version of AppCenter. By now I test the app by myself on fresh 5.1.6 and then submit it to the store to review. The next step is kinda magic for me.

I'm sad that gave you such a disappointing first experience

**Comment by megatux** [comment]
@amka it's totally understandable the current situation, just added a recommendation in case there was something that could help to improve the overall process. Don't worry, I'm currently using & enjoying the app. Thanks a lot for this.

**Comment by amka** [comment]
@megatux @janxkoci new release available at the appcenter, try to install it.

**Comment by megatux** [comment]
Upgraded to v 0.4.7 ,  this is the output now:
```
$ com.github.tenderowl.norka
Traceback (most recent call last):
  File "/usr/bin/com.github.tenderowl.norka", line 47, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
```

**Comment by amka** [comment]
@megatux that's weird. Do you use elementary OS 5.1.7? Did you try to remove the app completely and then reinstall it?

**Comment by megatux** [comment]
@amka tried with a "clean" user account and *worked*. Thanks
Although, opening the app from this user on a diff. X server without permissions gave me a Seg Fault. After an `xhost +` it worked. Maybe you can check that.
About my normal user, maybe the Python env. was non-eos-standard... I use _asdf_ version manager to have several installed versions of tools & languages.
I can give you more details if needed. I'm not a Python developer.

**Comment by janxkoci** [comment]
So for me the issue is gone, update went through okay and the app runs well now. Closing.
