### ISSUE TITLE
Change required for AppCenter: Don't mention "elementary"

### ISSUE THREAD

**Issue by cassidyjames** [TenderOwl/Norka#25]
Thanks for submitting your 0.4.6 update to AppCenter! However, while reviewing the submission, we found an issue that needs to be resolved.

https://github.com/TenderOwl/Norka/blob/d34b69492df72ec7b199d18a95fbdb8c3eaa539d/data/com.github.tenderowl.norka.appdata.xml.in#L49
https://github.com/TenderOwl/Norka/blob/d34b69492df72ec7b199d18a95fbdb8c3eaa539d/data/com.github.tenderowl.norka.appdata.xml.in#L57

As noted in the [Publishing Requirements → Metadata Requirements](https://docs.elementary.io/develop/appcenter/publishing-requirements#metadata-requirements), app metadata should not mention elementary. In rare, legitimate cases, mentions must abide by the [elementary Brand Guidelines](https://elementary.io/brand). I realize this was also used in previous release descriptions and appears to have been missed in a previous review. However, all instances should be removed to pass review. At the very least, ensure your usage follows the brand requirements, and it can be re-evaluated when re-submitted.

Once you've made the requested changes, create a new release on GitHub and re-submit it to the [AppCenter Dashboard](https://developer.elementary.io). As always, if you have any questions you can reply here.

**Comment by amka** [comment]
I must admit I read them over a year ago. Thanks for reminding :)

**Comment by cassidyjames** [comment]
No worries. :) Thanks for the quick turnaround! 0.4.7 has been approved.
