### ISSUE TITLE
Ctrl+W on listing changes toolbar. Bug?

### ISSUE THREAD

**Issue by megatux** [TenderOwl/Norka#29]
Steps to reproduce:

* On main screen, press Ctrl+W several times

![Captura de pantalla de 2020-08-27 11-28-58](https://user-images.githubusercontent.com/850020/91455534-930b9f80-e858-11ea-87e3-d53d4a6ed3e1.png)
![Captura de pantalla de 2020-08-27 11-28-46](https://user-images.githubusercontent.com/850020/91455543-943ccc80-e858-11ea-800b-b85e5c6245bf.png)

**Comment by amka** [comment]
Hey! Yeah, looks like a bug, thank you!

**Comment by amka** [comment]
Fixed in 0.5.0
