### ISSUE TITLE
Limit GtkSourceView width

### ISSUE THREAD

**Issue by dar5hak** [TenderOwl/Norka#36]
When running Norka in a maximized window, the GtkSourceView takes the entire width of the window, thus making the lines of text look lengthy. This makes them difficult to read.

Is it possible to center the GtkSourceView and limit its width? We might need to decide how exactly to limit:

- by character count per line
- percentage of screen size
- raw pixels

I'm not sure which one is the simplest to implement, but considering that `Gtk.SourceView` is a subclass of `Gtk.Widget`, raw pixels shouldn't be hard.

**Comment by amka** [comment]
@dar5hak  that's a good point and one of the next features. My thoughts stick around raw pixels maybe a 1000 width, but I need some time to decide, 'cause my monitor more than 3k wide :smiley:  Feel free to share your ideas.

**Comment by dar5hak** [comment]
@amka if it's 3k wide, does the OS use pixel doubling? In that case, 1000px would still be fine because it would occupy 2000px. You could test it and see what happens.

**Comment by amka** [comment]
@dar5hak no, it's not doubled, just a regular ultra-wide display :) Anyway, will test 1k width for its usability and will let you know.

**Comment by amka** [comment]
On my ultrawide display, it looks ok for me :)
![Снимок экрана от 2020-09-18 23 47 35](https://user-images.githubusercontent.com/519146/93643802-5f600780-fa09-11ea-9f6e-fae27c980095.png)

**Comment by dar5hak** [comment]
This looks so beautiful! ✨

Thank you! Feel free to close this issue when you're satisfied with the implementation.

**Comment by amka** [comment]
Goes to next release.
