### ISSUE TITLE
Norka does not add "." in the extension when exporting as markdown

### ISSUE THREAD

**Issue by khrynczenko** [TenderOwl/Norka#41]
Norka version: 0.6.2
OS: Pop 20.10

When I try to export a document as a markdown file, the name of the exported file does not have the dot symbol after the document name and before the extension. Example:
1) I have a document named *Prolog*
2) I export it as a markdown
3) The created file has the name *Prologmd* 
I would expect it to be *Prolog.md*
 
This does not occur when exporting as text/html files.
 
If you need any more information or if that is intentional please let me know :smile:.

**Comment by amka** [comment]
Thank you. What's the store you used to get Norka?

**Comment by khrynczenko** [comment]
I used [flatpak](https://www.flatpak.org/). Thank you for the quick fix :+1: .
