### ISSUE TITLE
Change required for AppCenter: Screenshots should not contain marketing copy

### ISSUE THREAD

**Issue by cassidyjames** [TenderOwl/Norka#44]
Thanks for submitting your 0.7.2 update to AppCenter! However, while reviewing the submission, we found an issue that needs to be resolved.

Your new screenshots referenced in your AppData contain non-full window screenshots, backgrounds, and marketing copy. Screenshots should only contain screenshots of the app window in use, and are not designed to be used for marketing copy or other illustrations. See the [AppCenter Publishing Requirements](https://docs.elementary.io/develop/appcenter/publishing-requirements#appdata-and-oars) for more details.

Once you've made the requested changes, create a new release on GitHub and re-submit it to the [AppCenter Dashboard](https://developer.elementary.io). As always, if you have any questions you can reply here.

**Comment by amka** [comment]
Ah, sure. Well, I will try to separate screenshots for the Snap Store and the AppCenter. 
By the way, maybe you could point me why did you make that decision?

**Comment by cassidyjames** [comment]
@amka screenshots are [part of the AppStream specification](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-screenshots) that we (and Flathub) use; it's not a "marketing graphic" spec, but is explicitly intended for screenshots of the application.

In general, elementary enforces things more strictly in AppCenter than other remotes like Flathub because the curation and consistency is a significant part of the allure of our platform. We specifically enforce this rule in AppCenter because we want potential users to be able to actually see the app they are going to install instead of seeing marketing graphics—plus the marketing copy inside of screenshots is neither translatable nor accessible to screen readers.
