### ISSUE TITLE
Location of saved files

### ISSUE THREAD

**Issue by Brin-o** [TenderOwl/Norka#45]
Hi! 

I currently have the appcenter version of the app and was wondering where the files get saved to *when they are not exported*. I want to set up some syncing so the chance of losing them is lower.

**Comment by amka** [comment]
Hey there! Sure, it's easy to find out what folder is used. To do that just run Norka from the terminal and you will see the notice where is the storage placed in your system. 

I'm working on cloud sync and local backup features, so I hope it will make you more confident about Norka's  internal storage.

Thank you for choosing Norka!

**Comment by Brin-o** [comment]
Thank you very much! That sounds exciting and I'm happy to hear that you are working on updates :)

**Comment by Rombusevil** [comment]
Hey @amka I'm interested in the cloud sync feature. Is that being worked on?

**Comment by amka** [comment]
Cloud sync is still not available due to deciding what cloud provider do I wanna use. But local backup will be available as an option in the next release.

**Comment by amka** [comment]
I will close this issue and open a new one for the cloud sync feature.
