### ISSUE TITLE
Follow cursor position

### ISSUE THREAD

**Issue by Brin-o** [TenderOwl/Norka#46]
While writing things I tend to do use Ctrl + A and then the arrow keys to move to the start or the end of the document. I've found that doing this in norka does move the cursor to the start/end yet it does not move the document to that position.

In this gif I press CTRL + A and then LEFT to go to the end of the document yet the view does not update.
![norka-follow](https://user-images.githubusercontent.com/49071768/119995665-1f0c4c80-bfce-11eb-8227-731f20ea8181.gif)

**Comment by amka** [comment]
It's a bit tricky because Ctrl+A and Left don't move the cursor actually. But the next LEFT scrolls it to the end. I think it's better than nothing, I guess.
