### ISSUE TITLE
Request: Word Count/Character Count

### ISSUE THREAD

**Issue by Brin-o** [TenderOwl/Norka#47]
While writing a report yesterday I noticed that there is no way for me to tell how many words I have written. Since I was writing a report for university with a limited word count I had to tab into a separate website to check it.

Reading time is nice, but I think it would be nice to display word count besides it, maybe only when the text is selected?

![image](https://user-images.githubusercontent.com/49071768/119995846-51b64500-bfce-11eb-9ff6-98a1b7350179.png)

**Comment by amka** [comment]
The idea with selection stats sounds quite nicely. Generously I think it may be a better decision to make a Stats window or show stats in the subtitle part of the Header. I mean word/char counter.

**Comment by Brin-o** [comment]
I think putting it in the subtitle part of the header would be great, especially considering that right now it does not have a utilitarian use :)

**Comment by amka** [comment]
I decided to combine both options :) Thank you for the suggestion!

**Comment by amka** [comment]
Just to let you know about the dev version

![preview](https://user-images.githubusercontent.com/519146/122256332-a109da00-ced7-11eb-8cb7-66da2d65f4c1.mp4)

**Comment by amka** [comment]
Merged.
