### ISSUE TITLE
Lost my writing

### ISSUE THREAD

**Issue by MakeGnomeWebFaster** [TenderOwl/Norka#65]
Hi there. 

I created a document in Norka a few days ago then I edited it today. When I finished editing, I fiddled around with exporting options. Markdown was good but after exporting the document as pdf I realized that it exported the few days earlier version. I checked it on Norka and it was reverted to that earlier version there as well. I couldn't replicate it again, but I thought it would be good to state this here because it is very critical if it is a bug.

Platform: eOS 6.1
Norka version is the latest one available on Appcenter
No custom modifications applied to the system

**Comment by amka** [comment]
@MakeGnomeWebFaster oh, I'm so sad to read this. I'm working on enabling autosave more often than now. As a small piece of advice: you can press `Ctrl+S` anytime you wanna save data.

**Comment by MakeGnomeWebFaster** [comment]
Since I couldn't replicate, I am closing this. Maybe it was something I did earlier. Anyway, thanks for this app!

**Comment by kov** [comment]
Should I reopen this ticket or create a new one? I am being hit by this issue when my whole session gets taken down (usually for running OOM, all those tabs...). Even if I have stopped writing for hours, the contents will not have been saved.

It's good to know about C-s, but it would be great to have some visual indication so I don't just become a paranoid doing C-s all the time. Did you end up finishing that work to enable autosave more often @amka? I think just saving a couple seconds after the last key stroke should work well enough, as it should not harm the interactivity of the app. I have 1.0.1. Thank you for Norka!

**Comment by amka** [comment]
Oh, snap! So sorry about this. It pushes me to make it more often and clear to the user.
