### ISSUE TITLE
Implement i18n

### ISSUE THREAD

**Issue by amka** [TenderOwl/Norka#9]
While most of the users can read the English words in the interface it could be really useful to have i18n for a better experience.

**Comment by megatux** [comment]
I can help with Spanish

**Comment by amka** [comment]
@megatux Sounds awesome! My thought to add i18n in the next release, your help will be appreciated.

**Comment by amka** [comment]
@megatux localization part is now built-in. Feel free to add Spanish translation and submit a PR.

**Comment by megatux** [comment]
Added PR #30 for this :+1:
