### ISSUE TITLE
appdata links to wrong url

### ISSUE THREAD

**Issue by Aman9das** [TenderOwl/Norka#92]
https://github.com/TenderOwl/Norka/blob/55e8812923cedce19c60956971196690c8203fe4/data/com.github.tenderowl.norka.appdata.xml.in#L28

Kindly fix

**Comment by Fingel** [comment]
https://fedoramagazine.org/fedora-linux-flatpak-cool-apps-to-try-for-april/

Discussion in the comments section on here is whether or not that is a scam site. Perhaps just unfinished?
